### ISSUE TITLE
promises

### ISSUE THREAD

**Issue by cjessett** [dmullin/codeacademy#2]
(Simplify) [This](https://github.com/dmullin/codeacademy/blob/b7dc50dd70d2221d657081d389cc0ad0a08ba4a2/projects/jammming/src/Util/Spotify.js#L72) and the one below do not need to be nested inside of a `.then`. Since promises are chain-able, you can just return the `fetch` above, then chain this `.then` on to the one it is inside of now.

**Comment by dmullin** [comment]
i believe I altered the code to what you were saying
