### ISSUE TITLE
modifying state

### ISSUE THREAD

**Issue by cjessett** [dmullin/codeacademy#3]
(important) [Here](https://github.com/dmullin/codeacademy/blob/b7dc50dd70d2221d657081d389cc0ad0a08ba4a2/projects/jammming/src/components/App/App.js#L30) you are modifying state directly with `.push`. The React docs specifically warn against this. Instead, create a new array with the desired tracks and use `.setState` like you did below.

**Comment by dmullin** [comment]
I believe that solved the issue
